kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zarinpal-v4-demo-admin
  namespace: zarinpal-v4-demo
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]